#!/usr/bin/env bash
set -euo pipefail

NAME=""
TARGET_PATH=""
BASE="both"

usage() {
  cat <<'EOF'
Usage:
  scaffold-linuxserver-image.sh --name <image-name> --path <target-path> --base <alpine|ubuntu|both>

Examples:
  scaffold-linuxserver-image.sh --name openclaw --path ./openclaw-linuxserver --base both
  scaffold-linuxserver-image.sh --name myapp --path . --base alpine
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --name)
      NAME="$2"; shift 2 ;;
    --path)
      TARGET_PATH="$2"; shift 2 ;;
    --base)
      BASE="$2"; shift 2 ;;
    -h|--help)
      usage; exit 0 ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1 ;;
  esac
done

if [[ -z "$NAME" || -z "$TARGET_PATH" ]]; then
  echo "--name and --path are required" >&2
  usage
  exit 1
fi

case "$BASE" in
  alpine|ubuntu|both) ;;
  *)
    echo "--base must be one of: alpine, ubuntu, both" >&2
    exit 1 ;;
esac

# normalize service slug
SLUG="$(echo "$NAME" | tr '[:upper:]' '[:lower:]' | tr ' _' '-' | sed 's/[^a-z0-9-]//g')"

mkdir -p "$TARGET_PATH"
cd "$TARGET_PATH"

mkdir -p \
  root/etc/s6-overlay/s6-rc.d/init-${SLUG} \
  root/etc/s6-overlay/s6-rc.d/svc-${SLUG}

cat > root/etc/s6-overlay/s6-rc.d/init-${SLUG}/run <<EOF
#!/usr/bin/with-contenv bash
set -euo pipefail

echo "[init-${SLUG}] preparing /config"
mkdir -p /config
chown -R abc:abc /config || true
EOF
chmod +x root/etc/s6-overlay/s6-rc.d/init-${SLUG}/run

cat > root/etc/s6-overlay/s6-rc.d/svc-${SLUG}/run <<EOF
#!/usr/bin/with-contenv bash
set -euo pipefail

# Replace with real app start command
exec echo "TODO: start ${SLUG} service"
EOF
chmod +x root/etc/s6-overlay/s6-rc.d/svc-${SLUG}/run

cat > root/etc/s6-overlay/s6-rc.d/svc-${SLUG}/type <<EOF
longrun
EOF

cat > root/etc/s6-overlay/s6-rc.d/init-${SLUG}/type <<EOF
oneshot
EOF

mkdir -p root/etc/s6-overlay/s6-rc.d/user/contents.d
cat > root/etc/s6-overlay/s6-rc.d/user/contents.d/init-${SLUG} <<EOF
EOF
cat > root/etc/s6-overlay/s6-rc.d/user/contents.d/svc-${SLUG} <<EOF
EOF

if [[ "$BASE" == "alpine" || "$BASE" == "both" ]]; then
cat > Dockerfile.alpine <<EOF
FROM ghcr.io/linuxserver/baseimage-alpine:3.22

ARG BUILD_DATE
ARG VERSION
ARG OPENCLAW_VERSION=latest
LABEL build_version="Linuxserver.io version:- \${VERSION} Build-date:- \${BUILD_DATE}" \
      org.opencontainers.image.title="${SLUG}" \
      org.opencontainers.image.description="LSIO-style ${SLUG} image" \
      org.opencontainers.image.source="https://github.com/yourorg/${SLUG}"

# TODO: install runtime deps
RUN apk add --no-cache bash curl

COPY root/ /

VOLUME /config
EXPOSE 3000
EOF
fi

if [[ "$BASE" == "ubuntu" || "$BASE" == "both" ]]; then
cat > Dockerfile.ubuntu <<EOF
FROM ghcr.io/linuxserver/baseimage-ubuntu:noble

ARG BUILD_DATE
ARG VERSION
ARG OPENCLAW_VERSION=latest
LABEL build_version="Linuxserver.io version:- \${VERSION} Build-date:- \${BUILD_DATE}" \
      org.opencontainers.image.title="${SLUG}" \
      org.opencontainers.image.description="LSIO-style ${SLUG} image" \
      org.opencontainers.image.source="https://github.com/yourorg/${SLUG}"

# TODO: install runtime deps
RUN apt-get update \
  && apt-get install -y --no-install-recommends bash curl ca-certificates \
  && rm -rf /var/lib/apt/lists/*

COPY root/ /

VOLUME /config
EXPOSE 3000
EOF
fi

cat > docker-bake.hcl <<EOF
group "default" {
  targets = ["alpine", "ubuntu"]
}

target "alpine" {
  dockerfile = "Dockerfile.alpine"
  tags = ["ghcr.io/yourorg/${SLUG}:alpine", "ghcr.io/yourorg/${SLUG}:latest"]
  platforms = ["linux/amd64", "linux/arm64"]
}

target "ubuntu" {
  dockerfile = "Dockerfile.ubuntu"
  tags = ["ghcr.io/yourorg/${SLUG}:ubuntu"]
  platforms = ["linux/amd64", "linux/arm64"]
}
EOF

mkdir -p .github/workflows
cat > .github/workflows/build.yml <<'EOF'
name: build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Build with bake
        run: docker buildx bake --print
EOF

cat > README.md <<EOF
# ${SLUG}

LinuxServer.io-style image scaffold generated by linuxserver-image-scaffold skill.

## Variants
- Alpine: \
  $( [[ -f Dockerfile.alpine ]] && echo "yes" || echo "no" )
- Ubuntu: \
  $( [[ -f Dockerfile.ubuntu ]] && echo "yes" || echo "no" )

## Next steps
1. Replace placeholder labels and source URL.
2. Add app install/runtime commands in Dockerfile(s).
3. Replace svc run command with real service start.
4. Test with docker build.
EOF

echo "Scaffold created at: $TARGET_PATH"
echo "Image slug: $SLUG"
